### ISSUE TITLE
Not working on Android 13

### ISSUE THREAD

**Issue by abhishek3x** [Henry-ZHR/force_dark#1]
App no longer works in Android 13

**Comment by Henry-ZHR** [comment]
~~Seems the setting (Override force-dark) in developer options doesn't work either~~

~~Not sure about what they've changed in Android 13~~

Maybe I did something wrong

**Comment by Typhonling** [comment]
Force-dark in developer options still works on Lineage OS 20. But this app doesn't work anymore.

**Comment by Henry-ZHR** [comment]
@Typhonling @abhishek3x Please test if this one works on your machines

~~[app-release.zip](https://github.com/Henry-ZHR/force_dark/files/10401952/app-release.zip)~~  Use the one below

**Comment by Henry-ZHR** [comment]
At least it works on my emulator with LSPosed

**Comment by Typhonling** [comment]
Excellent! It works well now.

**Comment by Henry-ZHR** [comment]
@Typhonling Also try this please [app-release.zip](https://github.com/Henry-ZHR/force_dark/files/10402175/app-release.zip)

**Comment by Typhonling** [comment]
Still works fine.
