### ISSUE TITLE
Not working on Miui14（Android 13）

### ISSUE THREAD

**Issue by chenxiccc** [Henry-ZHR/force_dark#2]
Not working on Miui14（Android 13）
Device: Xiaomi mix fold 2
Os: Miui 14.0.3

**Comment by Henry-ZHR** [comment]
What framework?

And Xposed log & `/system/framework/framework.jar` please

**Comment by chenxiccc** [comment]
[LSPosed_2023-02-16T21_30_51.213097.zip](https://github.com/Henry-ZHR/force_dark/files/10756597/LSPosed_2023-02-16T21_30_51.213097.zip)
[framework.zip](https://github.com/Henry-ZHR/force_dark/files/10756611/framework.zip)
FYI

**Comment by Henry-ZHR** [comment]
![](https://user-images.githubusercontent.com/51886614/219554330-413567e7-4b59-47d4-a9a5-b627df09aad3.png)

Not sure what MIUI do in `ForceDarkHelperStub`, but I think this may be the reason

And, it seems that MIUI has its own per-app dark option? Doesn't that work?

---

And, does the option in developer settings work for your target apps?

**Comment by chenxiccc** [comment]
The miui's dark mode by per-app only supports a few apps not all apps since miui13. And it only functions after you enabled the system dark mode. 

I use force dark cause i'd prefer to force some app（com.sohu.inputmethod.sogou.xiaomi）  into dark mode **without** system dark mode enabled.

I found nothing about “smart dark” or “force dark” or something like that in developer mode.

**Comment by Henry-ZHR** [comment]
预期行为，ForceDark 只有在系统暗黑模式开着的情况下才有用（~~其实我之前以为 Android 13 本来 ForceDark 就挂了也是因为这个~~）

~~看看 <https://github.com/KieronQuinn/DarQ> 之类的？~~ 没事了，他们也要开系统暗黑模式

---

README 都有中文了，没要求英文就别用英文开 issue 了，咱俩都难受。。。
