### ISSUE TITLE
有一些App不能够正常显示暗色

### ISSUE THREAD

**Issue by brijagstu7** [Henry-ZHR/force_dark#4]
比如新版本的云闪付、中国联通、支付宝

**Comment by Henry-ZHR** [comment]
1. 截图
2. 你期望的效果？

**Comment by brijagstu7** [comment]
![Screenshot_20230402-213001.png](https://user-images.githubusercontent.com/56994423/229355924-80cf9b5d-e50e-40e6-acef-cd2ad5c78ff2.png)
就是勾选了作用域跟没有勾选完全没有区别啊；
希望白变黑，黑变白
机型：一加7、摩托罗拉x30pro

**Comment by Henry-ZHR** [comment]
先确认开了暗黑模式（系统那个，不是模块），那个不开的话模块是没有作用的

然后试一下开发者选项里的 强制启用 SmartDark，这个开了也不变黑就是 app 或者系统问题

**Comment by brijagstu7** [comment]
强制覆盖smartdark开了也没用，这样的话还有什么办法吗

**Comment by Henry-ZHR** [comment]
那就是不行
