### ISSUE TITLE
Not working on android 13 October release and higher.

### ISSUE THREAD

**Issue by Yet-another-NPC-guy** [Henry-ZHR/force_dark#5]
Module not works.

**Comment by Henry-ZHR** [comment]
It works on my machine

![](https://github.com/Henry-ZHR/force_dark/assets/51886614/221c4cb6-1106-41c9-99e0-b471635b2188)

([ClipboardWhitelist](https://github.com/Kr328/Riru-ClipboardWhitelist) v19, which has no native dark theme support)
